#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Dec 18 18:39:29 MST 2020
# SW Build 2729669 on Thu Dec  5 04:48:12 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_Div_64bit_behav -key {Behavioral:Div_64:Functional:tb_Div_64bit} -tclbatch tb_Div_64bit.tcl -log simulate.log"
xsim tb_Div_64bit_behav -key {Behavioral:Div_64:Functional:tb_Div_64bit} -tclbatch tb_Div_64bit.tcl -log simulate.log

