webtalk_init -webtalk_dir /home/spencer/Documents/GitHub/UofCProjectHermes/eBPF_Core/eBPF_Core.sim/Adder_32/behav/xsim/xsim.dir/tb_Adder_32bit_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec  1 13:38:39 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2729669" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "39983417-4fde-4161-a5b3-7bef2ec37f53" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b1d78080d7e346308dc6047affadb438" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM)2 Duo CPU     E6550  @ 2.33GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1994.937 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "3.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "280 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "126148_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1915077128 -regid "" -xml /home/spencer/Documents/GitHub/UofCProjectHermes/eBPF_Core/eBPF_Core.sim/Adder_32/behav/xsim/xsim.dir/tb_Adder_32bit_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/spencer/Documents/GitHub/UofCProjectHermes/eBPF_Core/eBPF_Core.sim/Adder_32/behav/xsim/xsim.dir/tb_Adder_32bit_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/spencer/Documents/GitHub/UofCProjectHermes/eBPF_Core/eBPF_Core.sim/Adder_32/behav/xsim/xsim.dir/tb_Adder_32bit_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
