@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Jan 19 15:35:29 -0700 2021
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim Adder_Subtractor_64bit_behav -key {Behavioral:ALU:Functional:Adder_Subtractor_64bit} -tclbatch Adder_Subtractor_64bit.tcl -log simulate.log"
call xsim  Adder_Subtractor_64bit_behav -key {Behavioral:ALU:Functional:Adder_Subtractor_64bit} -tclbatch Adder_Subtractor_64bit.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
