#
# Copyright (c) 2020. Eidetic Communications Inc.
# All rights reserved.
#

- name: Install hermes
  block:
    - name: Create temporary directory
      tempfile:
        state: directory
      register: tmpdir

    - name: Clone eid-hermes repository
      git:
        repo: https://github.com/Eideticom/eid-hermes.git
        depth: 1
        recursive: no
        dest: "{{ tmpdir.path }}"
        accept_hostkey: true

    - name: Compile Hermes driver
      make:
        chdir: "{{ tmpdir.path }}/src/driver"

    - name: Install Hermes driver
      become: yes
      make:
        target: install
        chdir: "{{ tmpdir.path }}/src/driver"

  always:
    - name: Cleanup
      file:
        path: "{{ tmpdir.path }}"
        state: absent

- name: Load hermes driver
  become: yes
  modprobe:
    name: hermes
    state: present
