#
# Copyright (c) 2020. Eidetic Communications Inc.
# All rights reserved.
#

- name: Install xdma
  block:
    - name: Create temporary directory
      tempfile:
        state: directory
      register: tmpdir

    - name: Clone aws-fpga repository
      git:
        repo: https://github.com/aws/aws-fpga
        depth: 1
        recursive: no
        dest: "{{ tmpdir.path }}"
        accept_hostkey: true
        version: v1.4.17

    - name: Add Hermes to list of devices supported by xdma driver
      lineinfile:
        path: "{{ tmpdir.path }}/sdk/linux_kernel_drivers/xdma/xdma_mod.c"
        insertafter: '.*pci_ids\[\] = {.*'
        line: '{ PCI_DEVICE(0x1de5, 0x3000), },'

    - name: Compile XDMA driver
      make:
        chdir: "{{ tmpdir.path }}/sdk/linux_kernel_drivers/xdma"

    - name: Install XDMA driver
      become: yes
      make:
        target: install
        chdir: "{{ tmpdir.path }}/sdk/linux_kernel_drivers/xdma"

  always:
    - name: Cleanup
      file:
        path: "{{ tmpdir.path }}"
        state: absent

- name: Load xdma driver
  become: yes
  modprobe:
    name: xdma
    state: present
